---
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        args:
          - --extra-keys "kernelspec metadata.kernelspec metadata.interpreter"
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
      - id: nbqa-yapf
        additional_dependencies: 
          - toml
          - yapf