title: "Chess Engine 2"
author: Jens Heinrich and Leon De Andrade
# execute:
#   execute_notebooks: 'off'

latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: studienarbeit.tex

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    latex_logo: dhbw.png
    latex_theme: 'howto'
    nb_render_priority:
      latex:
        - "application/pdf"
        - "image/svg+xml"
        - "image/png"
        - "image/jpeg"
        - "text/latex"
        - "text/markdown"
        - "text/plain"
  extra_extensions:
    - sphinxcontrib.inkscapeconverter
