title: "Building an artificial intelligence for chess in python"
author: Jens Heinrich (9016280) and Leon De Andrade (1609922)
execute:
    timeout: 300
#   execute_notebooks: 'off'

only_build_toc_files: true

latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: studienarbeit.tex

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    latex_elements:
      # https://tex.stackexchange.com/questions/43024/section-results-in-0-1-not-in-1-0
      # https://tex.stackexchange.com/questions/9497/start-new-page-with-each-section
      preamble: |
        \renewcommand\thesection{\arabic{section}}
        \usepackage{titlesec}
        \newcommand{\sectionbreak}{\clearpage}
      papersize: a4paper
    latex_logo: dhbw.png
    latex_theme: 'howto'
    nb_render_priority:
      latex:
        - "application/pdf"
        - "image/svg+xml"
        - "image/png"
        - "image/jpeg"
        - "text/latex"
        - "text/markdown"
        - "text/plain"
  extra_extensions:
    - sphinxcontrib.inkscapeconverter